name: Run Unit Test and Upload Coverage Report

on:
  push:
    branches: 
      [main, pairA_design_part1]
  pull_request:
    branches: 
      [main, pairA_design_part1]
    types: [opened]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr

      - name: Configure CMake flags and build executables
        run: |
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
          cmake --build build/ --clean-first --target all test_coverage

      - name: Run tests and generate coverage report
        run: |
          ./build/test_executable # Replace with your test executable
          lcov --capture --directory . --output-file build/test_coverage.info # Ensure this matches your setup

      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Only for private repos
          files: ${{github.workspace}}/build/test_coverage.info
          fail_ci_if_error: true
          verbose: true
